# Homebrew Bundle File
#
# This is a Brewfile - used by Homebrew Bundle to install and manage packages,
# applications, and other dependencies in a single, declarative file.
#
# Usage:
# - Install everything: brew bundle
# - Check for missing packages: brew bundle check
# - List what would be installed: brew bundle list
#
# File structure:
# - brew: CLI tools and packages from Homebrew
# - mas: Mac App Store applications installed via 'mas' CLI
# - cask: Applications not available in App Store, installed via Homebrew Cask
#
# For more information: https://github.com/Homebrew/homebrew-bundle

## Utilities/Tools ##

brew "heroku"
brew "jq"
brew "mas"
brew "postgresql"
brew "pyenv"
brew "rbenv"
brew "rbenv-gemset"
brew "stow" # Installed via Makefile, listed for completeness
brew "tree"
brew "xq"
brew "git"
brew "git-lfs"

# App Store
mas "Amphetamine", id: 937984704
mas "Gifski", id: 1351639930

# TODO this works but adding a cask "mouseless" below does not
# brew install --cask mouseless

# !App Store
cask "1password-cli"
cask "alfred"
cask "crashplan"
cask "devonthink"
cask "emacs"
cask "google-cloud-sdk"
cask "iterm2"
cask "jordanbaird-ice"
cask "ngrok"
cask "rectangle"
cask "spotify"

